apiVersion: v1
kind: Service
metadata:
  name: smart-house-ai-frontend
spec:
  selector:
    app: smart-house-ai-frontend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP