image:
  repository: ghcr.io/jinsoooooooo/smart-house-ai/backend
  tag: "latest"
  pullPolicy: Always

service:
  port: 80
  targetPort: 8080

env:
  APP_NAME: "Smart House AI Backend"
  APP_HOST: "0.0.0.0"
  APP_PORT: "8080"
  APP_LOG_LEVEL: "debug"